apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: em-db-secrets   # IAM role via IRSA

      containers:
        - name: backend
          image: niki2003/employee-backend:latest
          ports:
            - containerPort: 8080

          # Load DB credentials from Kubernetes Secret (synced from AWS Secrets Manager)
          envFrom:
            - secretRef:
                name: em-db-secret

          # JWT also from secret (more secure)
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: em-db-secret
                  key: JWT_SECRET