apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: em-db-secrets   # IAM role via IRSA

      containers:
        - name: backend
          image: niki2003/employee-backend:latest
          ports:
            - containerPort: 8080

          # Load DB credentials from Kubernetes Secret (created via Secrets Manager)
          envFrom:
            - secretRef:
                name: em-db-secret

          # Optional: keep JWT here or move to Secrets Manager later
          env:
            - name: JWT_SECRET
              value: "abc123"

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "em-db-secrets"