apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: em-db-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "em-app-db"
        objectType: "secretsmanager"
        jmesPath:
          - path: host
            objectAlias: MYSQL_HOST
          - path: port
            objectAlias: MYSQL_PORT
          - path: dbname
            objectAlias: MYSQL_DB
          - path: username
            objectAlias: MYSQL_USER
          - path: password
            objectAlias: MYSQL_PASSWORD

  secretObjects:
  - secretName: em-app-db
    type: Opaque
    data:
      - objectName: MYSQL_HOST
        key: MYSQL_HOST
      - objectName: MYSQL_PORT
        key: MYSQL_PORT
      - objectName: MYSQL_DB
        key: MYSQL_DB
      - objectName: MYSQL_USER
        key: MYSQL_USER
      - objectName: MYSQL_PASSWORD
        key: MYSQL_PASSWORD