spring.application.name=Employee-Management

spring.datasource.url=jdbc:mysql://mysql-service:3306/employee_management?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=employeeuser
spring.datasource.password=nikhil@02

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connection-timeout=3000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=
spring.data.mongodb.auto-index-creation=false

server.port=8080

jwt.secret=abc12345

otel.service.name=employee-backend

otel.traces.exporter=none
otel.metrics.exporter=none
otel.logs.exporter=none